name = "adverserial"
description = "Ada Versatile Serialization"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

[build-switches]
"*".ada_version = "ada2022"
